<?xml version="1.0"?>

<!--
License: Apache 2.0. See LICENSE file in root directory.
Copyright(c) 2017 Intel Corporation. All Rights Reserved

This is the URDF model for the Intel RealSense 430 camera, in it's
aluminum peripherial evaluation case.
-->

<robot name="sensor_d435" xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- Includes -->
  <xacro:include filename="$(find turtlebot_description)/urdf/sensors/camera_gazebo.urdf.xacro"/>
  <xacro:include filename="$(find turtlebot_description)/urdf/sensors/laser_gazebo.urdf.xacro"/>
  <xacro:include filename="$(find turtlebot_description)/urdf/sensors/bumper_gazebo.urdf.xacro"/>
  
  <xacro:macro name="sensor_d435" params="parent name:=camera">
    <xacro:property name="M_PI" value="3.1415926535897931" />
  
    <!-- The following values are approximate, and the camera node
     publishing TF values with actual calibrated camera extrinsic values -->
    <xacro:property name="d435_cam_depth_to_infra1_offset" value="0.0"/>
    <xacro:property name="d435_cam_depth_to_infra2_offset" value="-0.050"/>
    <xacro:property name="d435_cam_depth_to_color_offset" value="0.015"/>

    <!-- The following values model the aluminum peripherial case for the
  	D435 camera, with the camera joint represented by the actual
  	peripherial camera tripod mount -->
    <xacro:property name="d435_cam_width" value="0.090"/>
    <xacro:property name="d435_cam_height" value="0.025"/>
    <xacro:property name="d435_cam_depth" value="0.02505"/>
    <xacro:property name="d435_cam_mount_from_center_offset" value="0.0149"/>

    <!-- The following offset is relative the the physical D435 camera peripherial
  	camera tripod mount -->
    <xacro:property name="d435_cam_depth_px" value="${d435_cam_mount_from_center_offset}"/>
    <xacro:property name="d435_cam_depth_py" value="0.0175"/>
    <xacro:property name="d435_cam_depth_pz" value="${d435_cam_height/2}"/>
    
    <!-- Asus mount -->
    <joint name="mount_asus_xtion_pro_joint" type="fixed">
      <origin xyz="0.11 0 0.272" rpy="0 0 0"/>
      <parent link="${parent}"/>
      <child link="mount_asus_xtion_pro_link"/>
    </joint>
    <link name="mount_asus_xtion_pro_link">
      <visual>
        <origin xyz="0 0 0" rpy="${-M_PI/2} 0 0"/>
        <geometry>
          <mesh filename="package://turtlebot_description/meshes/sensors/xtion_pro_stack.dae"/>
        </geometry>
      </visual>  
      <collision>
        <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
        <geometry>
        <!-- <box size="0.0330 0.2760 0.0120"/> -->
        <box size="0.0 0.0 0.0"/>
      </geometry>
      </collision>
      <inertial>
        <mass value="0.170" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.001152600" ixy="0.0" ixz="0.0"
                 iyy="0.000148934" iyz="0.0"
                 izz="0.001154654" />
      </inertial>
    </link>

    <!-- camera body, with origin at bottom screw mount -->
    <joint name="${name}_joint" type="fixed">
      <!-- <xacro:insert_block name="origin" /> -->
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <parent link="mount_asus_xtion_pro_link"/>
      <child link="${name}_bottom_screw_frame" />
    </joint>
    <link name="${name}_bottom_screw_frame"/>

    <joint name="${name}_link_joint" type="fixed">
      <origin xyz="0 ${d435_cam_depth_py} ${d435_cam_depth_pz}" rpy="0 0 0"/>
      <parent link="${name}_bottom_screw_frame"/>
      <child link="${name}_link" />
    </joint>

    <link name="${name}_link">
      <visual>
        <origin xyz="${d435_cam_mount_from_center_offset} ${-d435_cam_depth_py} 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
        <geometry>
          <!-- <box size="${d435_cam_width} ${d435_cam_height} ${d435_cam_depth}"/> -->
	        <mesh filename="package://turtlebot_description/meshes/sensors/d435.dae" />
        </geometry>
      </visual>
      <collision>
        <origin xyz="0 ${-d435_cam_depth_py} 0" rpy="0 0 0"/>
        <geometry>
          <box size="${d435_cam_depth} ${d435_cam_width} ${d435_cam_height}"/>
        </geometry>
      </collision>
      <inertial>
        <!-- The following are not reliable values, and should not be used for modeling -->
        <mass value="0.564" />
        <origin xyz="0 0 0" />
        <inertia ixx="0.003881243" ixy="0.0" ixz="0.0" iyy="0.000498940" iyz="0.0" izz="0.003879257" />
      </inertial>
    </link>

    <turtlebot_sim_3dsensor/>
    <turtlebot_sim_laser/>
    <turtlebot_sim_bumper/>
  </xacro:macro>
</robot>
