topic:
    laser_topic: '/scan'
    image_topic: '/camera/rgb/image_raw'
    agent_pub_topic: '/cmd_vel'
    gazebo_topic: '/gazebo/model_states'
    gazebo_set_topic: '/gazebo/set_model_state'
    
params:
    laser_size: 360
    img_size: 80
    num_sikp_frame: 2
    num_stack_frame: 4
    reward_near_goal: 1000
    reward_near_obs: -10

dist:
    laser_clip: 5.0
    goal_arrive: 1.0
    obs_safe: 1.2

learning:
    learning_rate: 0.01
    gamma: 0.9
    replace_target_iter: 200
    memory_size: 5000
    num_episode: 10000


